$axure.loadCurrentPage({
  "url":"全站分析.html",
  "generationDate":new Date(1414398641056.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8556e07901e14394a3f370e21ef9041a",
    "type":"Axure:Page",
    "name":"全站分析",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9249a7137b29475da3ec65191c64d201",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "size":{
              "width":1583,
              "height":60},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e36ebfa1a804ca8945bdea64ed42aaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "size":{
                  "width":1583,
                  "height":60},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全站分析/u0.png"}},
{
          "id":"0be26d4874474cf0a9c409378df0e7ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":170,
              "y":72},
            "size":{
              "width":200,
              "height":800},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72d61f08cae34b0881c41a7c0ca59fdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":170,
                  "y":72},
                "size":{
                  "width":200,
                  "height":800},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全站分析/u2.png"}},
{
          "id":"41034fe2295f4f51a71add413e1fd9d1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":130},
            "size":{
              "width":180,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/全站分析/u4_line.png"}},
{
          "id":"2fbc61bb54f14d23987b47ababf28fb4",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":80},
            "size":{
              "width":10,
              "height":792},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/全站分析/u5_line.png"}},
{
          "id":"207cb24366f34fea902ffadab7ab7c82",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":170,
              "y":82},
            "size":{
              "width":200,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fba3f30a46a04472bbbe982d6168663a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":170,
                  "y":82},
                "size":{
                  "width":200,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://10.0.22.102:8080/datakad/customer.html",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://10.0.22.102:8080/datakad/customer.html",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"第一时间",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/全站分析/u6.png",
            "mouseOver~":"images/全站分析/u6.png",
            "mouseDown~":"images/home/u10_mouseDown.png"}},
{
          "id":"ff513bcb8d514eda8f8265c4de22fa8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}}},
            "location":{
              "x":170,
              "y":141},
            "size":{
              "width":200,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df9bea72795d497abbe1aaf02895fc33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}}},
                "location":{
                  "x":170,
                  "y":141},
                "size":{
                  "width":200,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"第一时间",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "images":{
            "normal~":"images/全站分析/u8.png",
            "mouseOver~":"images/全站分析/u8.png",
            "mouseDown~":"images/home/u10_mouseDown.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9249a7137b29475da3ec65191c64d201":{
      "scriptId":"u0"},
    "4e36ebfa1a804ca8945bdea64ed42aaf":{
      "scriptId":"u1"},
    "0be26d4874474cf0a9c409378df0e7ad":{
      "scriptId":"u2"},
    "72d61f08cae34b0881c41a7c0ca59fdc":{
      "scriptId":"u3"},
    "41034fe2295f4f51a71add413e1fd9d1":{
      "scriptId":"u4"},
    "2fbc61bb54f14d23987b47ababf28fb4":{
      "scriptId":"u5"},
    "207cb24366f34fea902ffadab7ab7c82":{
      "scriptId":"u6"},
    "fba3f30a46a04472bbbe982d6168663a":{
      "scriptId":"u7"},
    "ff513bcb8d514eda8f8265c4de22fa8e":{
      "scriptId":"u8"},
    "df9bea72795d497abbe1aaf02895fc33":{
      "scriptId":"u9"}}});