$axure.loadCurrentPage({
  "url":"第一时间-官网.html",
  "generationDate":new Date(1414398640718.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6f20054f31c844578d32dca39dae04a1",
    "type":"Axure:Page",
    "name":"第一时间-官网",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c1bd33ce5aad485d833440f2bb3a00c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":72},
            "size":{
              "width":340,
              "height":1088},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5ad2011a53a4682924db378fa75719d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":72},
                "size":{
                  "width":340,
                  "height":1088},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"b906f98391774225adac24b3974237e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "paddingBottom":"20",
            "location":{
              "x":320,
              "y":72},
            "size":{
              "width":1150,
              "height":1068},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5de8c307c4d44cf693101cae0a788f83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "paddingBottom":"20",
                "location":{
                  "x":320,
                  "y":72},
                "size":{
                  "width":1150,
                  "height":1068},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"9249a7137b29475da3ec65191c64d201",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "size":{
              "width":1570,
              "height":60},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e36ebfa1a804ca8945bdea64ed42aaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "size":{
                  "width":1570,
                  "height":60},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"0be26d4874474cf0a9c409378df0e7ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":120,
              "y":72},
            "size":{
              "width":200,
              "height":800},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72d61f08cae34b0881c41a7c0ca59fdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":120,
                  "y":72},
                "size":{
                  "width":200,
                  "height":800},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u6.png"}},
{
          "id":"207cb24366f34fea902ffadab7ab7c82",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}}},
            "location":{
              "x":120,
              "y":72},
            "size":{
              "width":201,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":0,
              "blurRadius":5,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fba3f30a46a04472bbbe982d6168663a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}}},
                "location":{
                  "x":120,
                  "y":72},
                "size":{
                  "width":201,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://10.0.22.102:8080/datakad/customer.html",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://10.0.22.102:8080/datakad/customer.html",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"第一时间",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u8.png",
            "mouseOver~":"images/home/u8.png",
            "mouseDown~":"images/home/u8_mouseDown.png"}},
{
          "id":"ff513bcb8d514eda8f8265c4de22fa8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":120,
              "y":141},
            "size":{
              "width":200,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df9bea72795d497abbe1aaf02895fc33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":120,
                  "y":141},
                "size":{
                  "width":200,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 全站分析",
                      "target":{
                        "targetType":"page",
                        "url":"全站分析.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"第一时间",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u10.png",
            "mouseOver~":"images/home/u10.png",
            "mouseDown~":"images/home/u10_mouseDown.png"}},
{
          "id":"39bc98b665644faea25c0f7b0bbc6ca5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":340,
              "y":80},
            "size":{
              "width":130,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"734c8215968f44bcb88e8dc35984a1f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":340,
                  "y":80},
                "size":{
                  "width":130,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一时间-官网/u12.png"}},
{
          "id":"30849b75102846f0b38404130fc6dd52",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":131},
            "size":{
              "width":180,
              "height":1},
            "outerShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":1,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0ff0a6051c94617b8b6d16b228277eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":131},
                "size":{
                  "width":180,
                  "height":1},
                "outerShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":1,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u16.png"}},
{
          "id":"8d1d9adcbdea41d08fb4066ae0828852",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC6600}}},
            "location":{
              "x":1199,
              "y":84},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9fe717c8d8d47cea56d0e55a64e6745",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCC6600}}},
                "location":{
                  "x":1199,
                  "y":84},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u100.png",
            "mouseOver~":"images/home/u98_mouseOver.png"}},
{
          "id":"680fa3a8b0de4563a33e3ef4ea66dae0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC6600}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":1278,
              "y":84},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08ff01b61c854b1cbda7321d6be19fd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCC6600}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":1278,
                  "y":84},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 第一时间-官网",
                      "target":{
                        "targetType":"page",
                        "url":"第一时间-官网.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u98.png",
            "mouseOver~":"images/home/u98_mouseOver.png"}},
{
          "id":"01c435f269fa49cc9fc41e1943c2fb3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC6600}}},
            "location":{
              "x":1357,
              "y":84},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a73838b001044d94afc50b77cabb6214",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCC6600}}},
                "location":{
                  "x":1357,
                  "y":84},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u100.png",
            "mouseOver~":"images/home/u98_mouseOver.png"}},
{
          "id":"1e486de31a63488c9c8212a3d69c9efc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":120,
              "y":199},
            "size":{
              "width":200,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f8954b310564127b4bb91bebcb19677",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":120,
                  "y":199},
                "size":{
                  "width":200,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 全站分析",
                      "target":{
                        "targetType":"page",
                        "url":"全站分析.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"第一时间",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u10.png",
            "mouseOver~":"images/home/u10.png",
            "mouseDown~":"images/home/u10_mouseDown.png"}},
{
          "id":"19410fd7f98a4154b4803b362b05adf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":120,
              "y":363},
            "size":{
              "width":200,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ece95583d194c02b8619026310f3853",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":120,
                  "y":363},
                "size":{
                  "width":200,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 全站分析",
                      "target":{
                        "targetType":"page",
                        "url":"全站分析.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"第一时间",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u10.png",
            "mouseOver~":"images/home/u10.png",
            "mouseDown~":"images/home/u10_mouseDown.png"}},
{
          "id":"5da7a4f68e2d42d5aabaa0a1e3c680ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":120,
              "y":305},
            "size":{
              "width":200,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddab222449ed42f7937179939c1fd63c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":120,
                  "y":305},
                "size":{
                  "width":200,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 全站分析",
                      "target":{
                        "targetType":"page",
                        "url":"全站分析.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"第一时间",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u10.png",
            "mouseOver~":"images/home/u10.png",
            "mouseDown~":"images/home/u10_mouseDown.png"}},
{
          "id":"0c7cc0a13ea54295961e6055b16c480c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":119,
              "y":248},
            "size":{
              "width":200,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e5714405e9f4a5682a6eded2045a414",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":119,
                  "y":248},
                "size":{
                  "width":200,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 全站分析",
                      "target":{
                        "targetType":"page",
                        "url":"全站分析.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"第一时间",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u10.png",
            "mouseOver~":"images/home/u10.png",
            "mouseDown~":"images/home/u10_mouseDown.png"}},
{
          "id":"8b9d6f26870241a99fcec9245e84ead6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":120,
              "y":410},
            "size":{
              "width":200,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a41e407f04a442e9c8da259e7094c20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":120,
                  "y":410},
                "size":{
                  "width":200,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 全站分析",
                      "target":{
                        "targetType":"page",
                        "url":"全站分析.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"第一时间",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u10.png",
            "mouseOver~":"images/home/u10.png",
            "mouseDown~":"images/home/u10_mouseDown.png"}},
{
          "id":"9cdefcbecad74a6e90491d29880c5f69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":340,
              "y":122},
            "size":{
              "width":1097,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4136e8517a54df2a95b0bb0d8cf1b14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":340,
                  "y":122},
                "size":{
                  "width":1097,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一时间-官网/u32.png"}},
{
          "id":"49a14bce8dd04608aff41fce6aebfad1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":162},
            "size":{
              "width":1097,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c25e401e65d544c68b423b5151c9920e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":162},
                "size":{
                  "width":1097,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一时间-官网/u34.png"}},
{
          "id":"9a51fa22b6f142f8b40a1e72e52322c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":352,
              "y":128},
            "size":{
              "width":200,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5960a57318740989723c35ba39d513b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":352,
                  "y":128},
                "size":{
                  "width":200,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一时间-官网/u36.png"}},
{
          "id":"b4cd2862ad2446c3a1175a6c812547dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":340,
              "y":162},
            "size":{
              "width":180,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d8644d8cb474cbb863e0a4f06d0eb0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":340,
                  "y":162},
                "size":{
                  "width":180,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一时间-官网/u38.png"}},
{
          "id":"9337f52f4bba4fc3832650a71d074951",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":519,
              "y":162},
            "size":{
              "width":179,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbcf5aec328c413cadf6474d99d3f3bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":519,
                  "y":162},
                "size":{
                  "width":179,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一时间-官网/u40.png"}},
{
          "id":"daf4daedd24c49eba930a68a65e77518",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":858,
              "y":162},
            "size":{
              "width":181,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20afc2ea88cc407ab7f70c4232cee04d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":858,
                  "y":162},
                "size":{
                  "width":181,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一时间-官网/u42.png"}},
{
          "id":"f70651524f2c4d9592e592fea1d034a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":1038,
              "y":162},
            "size":{
              "width":139,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b8f8f78153842bbaf9f8bdee6727958",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":1038,
                  "y":162},
                "size":{
                  "width":139,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一时间-官网/u44.png"}},
{
          "id":"4a9d646186cf49d6b4f7580bb84e8741",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":697,
              "y":162},
            "size":{
              "width":162,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"098083a5c3a6497cb65936a628740e0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":697,
                  "y":162},
                "size":{
                  "width":162,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一时间-官网/u46.png"}},
{
          "id":"a1ba5281627f4140a8305458d819425b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":1176,
              "y":162},
            "size":{
              "width":139,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e934507527f947e7b602fd4a1f2d1d07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":1176,
                  "y":162},
                "size":{
                  "width":139,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一时间-官网/u44.png"}},
{
          "id":"d02dc4af43c54dd98f87e510d8c50b23",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":1314,
              "y":162},
            "size":{
              "width":123,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c17e61e0e8b04d9a9656144f97440b7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":1314,
                  "y":162},
                "size":{
                  "width":123,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一时间-官网/u50.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c1bd33ce5aad485d833440f2bb3a00c9":{
      "scriptId":"u0"},
    "d5ad2011a53a4682924db378fa75719d":{
      "scriptId":"u1"},
    "b906f98391774225adac24b3974237e2":{
      "scriptId":"u2"},
    "5de8c307c4d44cf693101cae0a788f83":{
      "scriptId":"u3"},
    "9249a7137b29475da3ec65191c64d201":{
      "scriptId":"u4"},
    "4e36ebfa1a804ca8945bdea64ed42aaf":{
      "scriptId":"u5"},
    "0be26d4874474cf0a9c409378df0e7ad":{
      "scriptId":"u6"},
    "72d61f08cae34b0881c41a7c0ca59fdc":{
      "scriptId":"u7"},
    "207cb24366f34fea902ffadab7ab7c82":{
      "scriptId":"u8"},
    "fba3f30a46a04472bbbe982d6168663a":{
      "scriptId":"u9"},
    "ff513bcb8d514eda8f8265c4de22fa8e":{
      "scriptId":"u10"},
    "df9bea72795d497abbe1aaf02895fc33":{
      "scriptId":"u11"},
    "39bc98b665644faea25c0f7b0bbc6ca5":{
      "scriptId":"u12"},
    "734c8215968f44bcb88e8dc35984a1f7":{
      "scriptId":"u13"},
    "30849b75102846f0b38404130fc6dd52":{
      "scriptId":"u14"},
    "f0ff0a6051c94617b8b6d16b228277eb":{
      "scriptId":"u15"},
    "8d1d9adcbdea41d08fb4066ae0828852":{
      "scriptId":"u16"},
    "c9fe717c8d8d47cea56d0e55a64e6745":{
      "scriptId":"u17"},
    "680fa3a8b0de4563a33e3ef4ea66dae0":{
      "scriptId":"u18"},
    "08ff01b61c854b1cbda7321d6be19fd7":{
      "scriptId":"u19"},
    "01c435f269fa49cc9fc41e1943c2fb3a":{
      "scriptId":"u20"},
    "a73838b001044d94afc50b77cabb6214":{
      "scriptId":"u21"},
    "1e486de31a63488c9c8212a3d69c9efc":{
      "scriptId":"u22"},
    "4f8954b310564127b4bb91bebcb19677":{
      "scriptId":"u23"},
    "19410fd7f98a4154b4803b362b05adf8":{
      "scriptId":"u24"},
    "1ece95583d194c02b8619026310f3853":{
      "scriptId":"u25"},
    "5da7a4f68e2d42d5aabaa0a1e3c680ff":{
      "scriptId":"u26"},
    "ddab222449ed42f7937179939c1fd63c":{
      "scriptId":"u27"},
    "0c7cc0a13ea54295961e6055b16c480c":{
      "scriptId":"u28"},
    "1e5714405e9f4a5682a6eded2045a414":{
      "scriptId":"u29"},
    "8b9d6f26870241a99fcec9245e84ead6":{
      "scriptId":"u30"},
    "9a41e407f04a442e9c8da259e7094c20":{
      "scriptId":"u31"},
    "9cdefcbecad74a6e90491d29880c5f69":{
      "scriptId":"u32"},
    "f4136e8517a54df2a95b0bb0d8cf1b14":{
      "scriptId":"u33"},
    "49a14bce8dd04608aff41fce6aebfad1":{
      "scriptId":"u34"},
    "c25e401e65d544c68b423b5151c9920e":{
      "scriptId":"u35"},
    "9a51fa22b6f142f8b40a1e72e52322c9":{
      "scriptId":"u36"},
    "d5960a57318740989723c35ba39d513b":{
      "scriptId":"u37"},
    "b4cd2862ad2446c3a1175a6c812547dc":{
      "scriptId":"u38"},
    "6d8644d8cb474cbb863e0a4f06d0eb0a":{
      "scriptId":"u39"},
    "9337f52f4bba4fc3832650a71d074951":{
      "scriptId":"u40"},
    "fbcf5aec328c413cadf6474d99d3f3bc":{
      "scriptId":"u41"},
    "daf4daedd24c49eba930a68a65e77518":{
      "scriptId":"u42"},
    "20afc2ea88cc407ab7f70c4232cee04d":{
      "scriptId":"u43"},
    "f70651524f2c4d9592e592fea1d034a8":{
      "scriptId":"u44"},
    "6b8f8f78153842bbaf9f8bdee6727958":{
      "scriptId":"u45"},
    "4a9d646186cf49d6b4f7580bb84e8741":{
      "scriptId":"u46"},
    "098083a5c3a6497cb65936a628740e0a":{
      "scriptId":"u47"},
    "a1ba5281627f4140a8305458d819425b":{
      "scriptId":"u48"},
    "e934507527f947e7b602fd4a1f2d1d07":{
      "scriptId":"u49"},
    "d02dc4af43c54dd98f87e510d8c50b23":{
      "scriptId":"u50"},
    "c17e61e0e8b04d9a9656144f97440b7c":{
      "scriptId":"u51"}}});